### ISSUE TITLE
Behavior of counsel-fd-dired-jump

### ISSUE THREAD

**Issue by linwaytin** [CsBigDataHub/counsel-fd#3]
When using this tool, I usually want to open the selected subdirectory in `dired`.
Currently `counsel-fd-dired-jump` opens the input directory in `dired` and moves the point to the selected subdirectory, and then I need to click some key to go into the wanted directory.
Could you please make an option so that it open the chosen subdirectory directly?
I think changing `dired-jump` to `dired` can make this.

Thanks for this great package.

**Comment by ChetanKoneru** [comment]
@linwaytin , Thanks for the issue. Yes this is an useful functionality.

**Comment by linwaytin** [comment]
Thanks!
